services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL= #optional
      - SERVERPORT=51820 #optional
      - PEERS=
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13 #optional
    volumes:
      - ./wireguard-config:/config
      - wireguard-data:/data
      - /usr/src:/usr/src:ro
    ports:
      - 51820:51820/udp
      - "127.0.0.1:27017:27017"
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
      - net.ipv4.conf.default.rp_filter=2
      - net.ipv6.conf.all.disable_ipv6=0
    restart: unless-stopped

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
      - wireguard-data:/data/wireguard:ro
    network_mode: container:wireguard

volumes:
  mongo-data:
    external: true
  wireguard-config:
    external: true
  wireguard-data:
    external: true